### ISSUE TITLE
Build Badge display issues

### ISSUE THREAD

**Issue by skylerto** [chef/scaffolding-chef#17]
# Describe the problem

Build badge isn't being displayed correctly.

![chef_scaffolding-chef__Best_practices_for_Chef_Infra_as_a_Habitat_package](https://user-images.githubusercontent.com/4228704/60032985-b09e1180-9675-11e9-8da6-f84d20c6dde2.png)

For anyone who isn't signed into the chef buildkite, the badge isn't being displayed correctly.

When visiting the link, getting prompted with the buildkite chef okta login.

![Authorization_Required__Chef_Software_Inc](https://user-images.githubusercontent.com/4228704/60033113-f1962600-9675-11e9-8094-d76841980a6f.png)

**Comment by echohack** [comment]
FYI: While I think your theory about buildkite auth is a good one, this is just the result of me not knowing how badges should actually be linked. Doh!

**Comment by skylerto** [comment]
Been there for sure! Looks good in the PR btw. 😄
